import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex">
          {/* nav bar */}
          <p>home</p>
          <p>01. resume</p>
          <p>02. projects</p>
          {/* or group into personal */}
          <p>03. my hub</p>
          {/* <p>03. reading</p>
          <p>04. writing</p>
          <p>05. gallery</p> */}
        </div>
        {children}
      </body>
    </html>
  );
}
